### PR TITLE
Issue71 simplify release process

### PR DESCRIPTION
**Pull request by jspaaks**
Made this PR to help make the discussion https://github.com/citation-file-format/citation-file-format/issues/71 a little more concrete.

Feel free to cancel the PR if we decide to go another route.

### CODE REVIEW

**Comment by jspaaks** [comment]
Went ahead and copied the specifications.md file for version 1.0.3 into here while retaining git history.  Removed the other files.

If possible, we should make specifications.md 'normal' markdown such that we can easily make changes, and other people can easily contribute by editing on github. I think I've decided we shouldnt have pdfs or anything fancy like jekyll pages

**Comment by jspaaks** [comment]
Note that the tests I just added can't fail because of how ``cffconvert==1.1.0`` catches exceptions at the moment (https://github.com/citation-file-format/cff-converter-python/issues/94)

**Comment by sdruskat** [comment]
TODOs before this can be merged:

- [ ] Check if this is up-to-date with the 1.0.3-4 release of the specs.

**Comment by jspaaks** [comment]
At least the schema is exactly equal:

```bash
# get bleeding edge schema 
curl https://raw.githubusercontent.com/citation-file-format/schema/master/CFF-Core/schema.yaml > old.yaml
# get this PR's schema
curl https://raw.githubusercontent.com/citation-file-format/citation-file-format/issue71-merge-repos/schema.yaml > new.yaml
# see if they are different
diff --report-identical-files old.yaml new.yaml
Files old.yaml and new.yaml are identical
```

Personally, I don't care a whole lot if the spec / the PDF is super equal, because as far as I'm concerned there is too much leeway in natural language anyway. If me and my colleagues are any indication, most people will scroll through the text of the spec until they see an example that looks like their use case, then copy-paste and be done. Less than half of them will validate the file. Virtually no-one will read the spec.

**Comment by sdruskat** [comment]
See your point.

One of the ways I can see this work better is to make the spec doc (README) more structured and clear out the clutter, i.e.,

- Let the README specs focus on the structure of the file, what *needs* to be in it, and what *can* be in it, more or less in list form with only minimum explanation where necessary, and as little free text as possible. Then, give examples.  
I think that this way people who have an interest in accessing the whole spec (e.g., to find out what fields the format provides for their use case) can use it more easily, and people who want to copy and paste can do that as well.
- Move the meta info about history, etc., to one or more pages in .github.io. The landing page there should look something like you describe in https://github.com/citation-file-format/citation-file-format/issues/76#issuecomment-478563936, with the meta info available in pages somewhere for those who are interested.

I'll give the first step a shot (the second can wait), and let you have a look.

**Comment by jspaaks** [comment]
Sounds good! I assume you'd like the cleaned-up version of the README to be part of 1.1.0?

**Comment by sdruskat** [comment]
> 
> 
> I assume you'd like the cleaned-up version of the README to be part of 1.1.0?

Yes, in fact I've thought about this over the last few days. We have conflicting requirements, in that 

- I'd like to be 1.1.0 a "complete" release, so as to not confuse the user with lots of version changes, with 
     1. the new repo structure, 
     2. the cleaned README, 
     3. the YAtiML schema (and tests)
- We should get the identifiers (#85) in in time for the workshop next week, as lots of registries will have their own non-DOI identifiers.

I think one way of doing this would be to work with milestone releases, i.e.,

- `1.1.0-M1`: The new repo structure, with a fix for #85 + possibly fixes for other small features that we want to pull in (identifiers are most important, and things like contributor roles are out of scope).
- `1.1.0-M2`: The cleaned README & new landing page
- `1.1.0-RC`: The YAtiML schema and tests
- `1.1.0`: The version that brings it all together and is tested to work and be usable (hopefully = -RC).

We could encourage the participants at the workshop to use the then current state of 1.1.0, even if it is only a milestone release, but it will have the identifier fields.

We could then do 1.2.0 for full CodeMeta compatibility at a later stage, and possibly pull in the contributor roles and other more heavyweight features then.

What do you think?

**Comment by jspaaks** [comment]
What I'd like to have for the workshop is the following:

- new repo structure with cleaned README
- new landing page (https://github.com/citation-file-format/citation-file-format/issues/76)
- bugs/ features:
   - identifiers (#85)
   - dois with slashes (https://github.com/citation-file-format/schema/pull/10, https://github.com/citation-file-format/schema/issues/9; apparently this didn't work before. I would be open to having regexps that are much more lenient, like we discussed for email addresses).

For the moment, I'd like to stay away from:
- contributor roles
- yatiml, even though it looks promising. Of course we can paint a picture of why it would be useful during a presentation. Note that I am not yet familiar with yatiml beyond having scanned the readme. I'd like to have some experience with it and some time to reflect on it as well, before going out into the world and advocating people should or shouldn't adopt it. Realistically, there is no time for that between now and the workshop.

I consider the above the 1.1.0 release. With it, we have enough materials to be interesting to people who are looking to implement, and easy enough to follow because they are all based on tooling that we have some experience with. For example, people can:
- initalize their CFF files with https://bit.ly/cffinit
- validate and convert with https://bit.ly/cffconvert or https://pypi.org/project/cffconvert/
- learn about a GitHub-Zenodo workflow with https://guide.esciencecenter.nl/citable_software/making_software_citable.html

Finally, I'd also like to go through the issues together, to see if we can make that list more presentable.

**Comment by jspaaks** [comment]
As a separate issue from the workshop, I'd like to develop some kind of strategy of how we are dealing with versions: what will be supported, for how long, what problems arise if we have lots of versions. Do we need release candidates, etc. I have little experience with thinking about this so I'm sure it's gonna be painful. From a development point of view, I think I'd like to make small releases, like for instance the ORCID-X one or the email address fix.

**Comment by jspaaks** [comment]
A final aspect I'd like to say something about is the conversion of metadata to other formats. The crosswalk table over at the CodeMeta project seems nice, but I'm not convinced it is actually helping anything. The conversion between the different columns is lossy, and don't forget that _each column_ is actually versioned. Furthermore, conversion between some keys can not be defined as a mapping like it is now, for example when the meaning of one key in a given format is approximated by not one but two keys in another. And conversion between other keys is just not possible: for example, splitting up a name into its constituent parts, like what is _Steven Van Zandt_'s last name? Does he have a name particle? What about _Steven van Zandt_? Pretty tricky stuff, you'll agree. And it only gets more difficult with non-western names I'm sure.

Generalizing over all of these cases is well beyond the scope of what we can do, or even of what can be done. And to what end do we even want to generalize? The idea that we can have one 'best' standard is naive, as is the idea that people who have a lot of data in a certain format are willing to adopt another standard. Especially data people are super conservative when it comes to retroactively making changes to the data.

In my opinion, metadata quality is served best if whoever is entering the data has some idea why they are doing it, and has access to the one or two places where it is used, so they can tweak their metadata for those use cases and immediately see whether their changes serve their purposes. I do not believe in optimizing anything absent a purpose: that cannot work. So I would advocate we must create tooling and standards that are optimized for simplicity, ease of use, and transparency. This is already a huge challenge btw.

**Comment by sdruskat** [comment]
> As a separate issue from the workshop, I'd like to develop some kind of strategy of how we are dealing with versions: what will be supported, for how long, what problems arise if we have lots of versions. Do we need release candidates, etc. I have little experience with thinking about this so I'm sure it's gonna be painful. From a development point of view, I think I'd like to make small releases, like for instance the ORCID-X one or the email address fix.

Agree that we should devise a plan here. Personally I like small releases, but am not sure if this will perhaps have negative effects on users and uptake ("wait, there's yet *another* version (1.1.14 of this 'standard' format? Why isn't it stable?"). This could perhaps be alleviated with sticking to SemVer, and letting users supply `cff-version` as just `1` or `1.1`, so down to minor or even just major version, promising that it won't break...

Perhaps we can start thinking about this at (after?) the workshop next week. Perhaps we could even ask attendees what they think.

**Comment by sdruskat** [comment]
> I consider the above the 1.1.0 release.

Fair enough, staying away from YAtiML for the minute. I've had a more thorough look at it before and it seems well-designed and suitable to what we need, but always better to try something for a bit before adopting it.

Let's make this 1.1.0 then.

> Finally, I'd also like to go through the issues together, to see if we can make that list more presentable.

Yes. When do you wanna do this. Before the workshop, remotely? I could do Monday, tomorrow and Friday are packed :(.

**Comment by jspaaks** [comment]
Regarding semver, reasoning about the intricacies of a range of versions at the same time is very difficult. I'd therefore advocate and also expect that people stick to exactly 1, fully-defined schema version (even though that version may have bugs that are already known at the time of writing the metadata, e.g. like we had with [ORCIDs ending in ``X``](https://github.com/citation-file-format/schema/issues/1), [dois without slashes](https://github.com/citation-file-format/citation-file-format/issues/92), etc.). 

IMO we should not allow metadata writers to just specify ``major`` or ``major.minor`` as this will surely lead to errors or in any case loss of specificity.

We should think about what type of change to the schema (or actually the full repository) warrants incrementing which part of the semver.

**Pull request merged**
