### PR TITLE
autocast number types

### PR DESCRIPTION
**Pull request by jspaaks**
**Related issues**

Refs: #91 

- This PR includes `148-sort-schema`/PR #218  and `lint-schema` / PR #201 branches. Merging PR #218 will clean up the diff for `schema.json`.
- Also awaiting better consensus after https://github.com/citation-file-format/citation-file-format/issues/91#issuecomment-865902434.

**Describe the changes made in this pull request**

from https://github.com/citation-file-format/citation-file-format/issues/91#issuecomment-865881061

Now that we have switched to JSONSchema, we should re-evaluate whether union types for some keys are useful. For example, it is currently (https://github.com/citation-file-format/citation-file-format/blob/38d9b1fb629373f6a3607de64aa3a6e21a76f750/schema.json) invalid to write the following in `CITATION.cff`:

```yaml
version: 1
```
```yaml
version: 1.11
```
```yaml
number: 41
```
```yaml
issue: 11
```

This is a bit unexpected and inconvenient for people particularly those who write CITATION.cff files by hand / unassisted.

I went over the keys and tried to identify a list of keys that could potentially have values that are interpreted as numbers by YAML, which would render them invalid. Here's the list I came up with:

1. `#/definitions/post-code`
1. `issue`
1. `number`
1. `reference/version`
1. `section`
1. `version`

This PR expands their `"type": "string"` to a `str|number` union type using JSONSchema `"anyOf"`.

This also meant that some of the tests were no longer necessary, specifically the tests that verify that certain `CITATION.cff` files do not pass validation. This PR removes those tests (from `examples/1.2.0/fail/**`)

**Instructions to review the pull request**

```shell
cd $(mktemp -d --tmpdir cff.XXXXXX)
git clone https://github.com/citation-file-format/citation-file-format .
git checkout 91-autocast-number-types
python3 -m venv env
source env/bin/activate
pip install --upgrade pip setuptools wheel
pip install -r requirements.txt
pytest
```

pytest should pass with 68 (not 70 like before) items discovered

### CODE REVIEW

**Review by sdruskat — COMMENTED** [review]
Think this needs a resolution of #91 per discussion before it can be reviewed, and may need more work after we've come to a decision there.

**Review by sdruskat — APPROVED** [review]
Thanks, excellent work.
Should we perhaps deduplicate `version` via a definition?

**Comment by jspaaks** [comment]
>  Should we perhaps deduplicate `version` via a definition? 

Created #226

**Comment by jspaaks** [comment]
Thanks for reviewing!

**Pull request merged**
