### PR TITLE
Sort fields in schema.json alphabetically

### LINKED ISSUE #148: sort keys in the jsonschema alphabetically
makes them easier to find, especially in longer lists

### PR DESCRIPTION
**Pull request by sdruskat**
**Related issues**

Fix #148

**Describe the changes made in this pull request**

- Use `cat schema.json | jq -S --indent 4 '.' > schema.json.new` +
`mv schema.json.new schema.json` to overwrite `schema.json` with
alphabetically sorted fields

**Instructions to review the pull request**

- Linting stage in #201 testing should now pass once rebased onto these changes
- All other tests should also pass
- Diff `schema.json` against the `1.2.0` branch to see if there's nothing broken :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by jspaaks** [comment]
Tested by 
```
cd $(mktemp -d --tmpdir cff.XXXXXX)
git clone https://github.com/citation-file-format/citation-file-format .
git checkout 1.2.0
cat schema.json | jq -S --indent 4 '.' > schema.sorted.json
git checkout 148-sort-schema-json 
diff schema.json schema.sorted.json 
```
`diff` result was empty, yay. Additionally I gave the `schema.json` a cursory inspection, looks good.

Should we wait with merging until the additional tests from PR #214 are merged?

**Comment by sdruskat** [comment]
> Should we wait with merging until the additional tests from PR #214 are merged?

:+1:

**Review by jspaaks — CHANGES_REQUESTED** [review]
Looks good but can you please merge `origin/1.2.0` into `148-sort-schema-json` so we can have more tests?

**Review by jspaaks — APPROVED** [review]
sorted bliss, thank you!

**Comment by sdruskat** [comment]
> sorted bliss, thank you!

Dto.!

**Pull request merged**
