### PR TITLE
[Enhancement] Turn Markdown Issue Templates into Forms (#1)

### PR DESCRIPTION
**Pull request by kevinmatthes**
**Related issues**

Refs: none

**Describe the changes made in this pull request**

This Pull Request applies a new feature of GitHub:  Issue Forms.  Since the issue templates of this repository have a form-like structure, it is a sane decision to apply this new feature.

The first commit is intended as a preview of how it will look when all Markdown templates are turned into forms.  Hence, it provides just one form:  the tooling template.

**Review checklist**

- [ ] Please check if the pull request is against the correct branch  
- [ ] Please check if all changes are recorded in `CHANGELOG.md` and adapt if necessary.
- [ ] Please run tests locally.
```bash
cd $(mktemp -d --tmpdir cff.XXXXXX)
git clone https://github.com/citation-file-format/citation-file-format .
git checkout <branch>
python3 -m venv env
source env/bin/activate
pip install --upgrade pip wheel setuptools
pip install -r requirements.txt
pytest
```
- [ ] Please visit https://github.com/kevinmatthes/citation-file-format/blob/feature/issue-forms/.github/ISSUE_TEMPLATE/30_tooling.yml for a preview of how the form is going to be shown to users.

### CODE REVIEW

**Comment by kevinmatthes** [comment]
As written in the description, this submission contains just one new form.  In case this suggestion is accepted, please tell me if and which other issue templates shall be turned into forms, as well.  I would then adjust the others, as well, and submit them in this Pull Request.

By the way:  the 99-blank.md template is not actually required since one can also choose to create a default template from the footer of the selector.  This can be turned off by a further configuration file in the respective directory.  Shall the 99-blank.md be kept and turned into form?  Shall the configuration be adjusted such that one is forced to use 99-blank.md instead of the default issue?

**Comment by kevinmatthes** [comment]
Due to the intention of the section "Implementation Suggestions", I marked this field optional.  All other fields are mandatory.  Shall I turn the sole optional field to mandatory, as well?

**Comment by sdruskat** [comment]
Thanks @kevinmatthes, for this PR! I like the look of the new form.

As for your questions, 

- I'd keep the *Implementation suggetions* field optional, as I assume that less technically experienced users with a tooling idea may have difficulties filling this in.
- I can see no immediate downsides with deleting the 99-blank.md template, so I'd be for it.

One thing I'm wondering is whether the early status of the forms schema (see [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema): *Issue forms are currently in beta for public repositories on GitHub.com only.*) means that perhaps we should wait until this has stabilized? I'm not assuming that this will likely meet the fate of the related issues dropdown and go away completely, but it would be a shame to waste energy on something that won't stick around in this form?

Would like to hear your thoughts on the latter, and from @jspaaks as well, as usual 😃.

**Comment by kevinmatthes** [comment]
An option would be to move the YAML forms to a new directory within this repository, say `yaml-forms/` in the repository root.  As soon as the beta phase of this feature is done, the YAML forms are already prepared and only need to be moved to the target directory in order to replace the old Markdown templates.

**Comment by kevinmatthes** [comment]
I am going to remove the blank template as discussed.  If my suggestion to prepare the YAML forms in a separate directory is accepted, I will also restore the replaced Markdown template for the tooling ideas in order to keep it until the beta phase is done.

**Comment by jspaaks** [comment]
Thanks @kevinmatthes for your work on this PR. Sorry for the long wait, it has been difficult to find the time lately.

1. I agree with Stephan on keeping the _Implementation suggetions_ field optional
2. I spawned issue https://github.com/citation-file-format/citation-file-format/issues/444 for the removing or keeping `99-blank.md` so we can discuss it there. Personally I'd like to keep it.
3. I'm not in favor of creating `yaml-forms`
4. I'm not too worried about the beta-ness of the forms feature, it wouldn't be all that difficult to resurrect issue templates from, say, 1.2.0 if need be.

**Comment by sdruskat** [comment]
Hi @kevinmatthes, thanks for this PR!

I agree with what Jurriaan said in https://github.com/citation-file-format/citation-file-format/pull/395#issuecomment-1621692826, so once https://github.com/citation-file-format/citation-file-format/pull/395/commits/d10614d61bd2449fc2b908fe939da65753a81416 is rolled back this is good to be merged 🎉! Do you want to do this yourself? Otherwise either me or @jspaaks could do it.

**Comment by kevinmatthes** [comment]
Thank you, @sdruskat, I will recreate the template in a moment. :+1:

**Comment by kevinmatthes** [comment]
Done. :+1:

**Comment by sdruskat** [comment]
Thanks for this PR and you continued engagement @kevinmatthes! It's much appreciated :).

**Comment by sdruskat** [comment]
Looks great IMHO:

grafik

**Pull request merged**
