### PR TITLE
codespell: action, config + 1 typo fixed -- to prevent any future typo being undetected

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by sdruskat** [comment]
Thanks for the PR @yarikoptic, this is surely useful.

Out of interest, why use codespell over the alternatives (e.g., https://github.com/marketplace/actions/github-spellcheck-action)?

@jspaaks, what do you think about adding this?

**Comment by yarikoptic** [comment]
well, I just don't have experience with that action and/or underlying https://facelessuser.github.io/pyspelling/ .  sounds like pyspelling might be doing full spellchecking whenever codespell just finds/suggests fixes for commonly made typos. As such, pyspelling might be more "complete" but codespell might be more robust but I could be proven to be wrong -- simply have no experience with pyspelling.

**Comment by jspaaks** [comment]
> Thanks for the PR @yarikoptic, this is surely useful.
> 
> Out of interest, why use codespell over the alternatives (e.g., https://github.com/marketplace/actions/github-spellcheck-action)?
> 
> @jspaaks, what do you think about adding this?

First off, let me say that I appreciate the work that @yarikoptic did to make this PR. And I'm happy to find out that spelling mistakes were not a big problem in this repo. So if the tool can be unobtrusive, I'm ok with merging this.

**Comment by sdruskat** [comment]
> First off, let me say that I appreciate the work that @yarikoptic did to make this PR. And I'm happy to find out that spelling mistakes were not a big problem in this repo. So if the tool can be unobtrusive, I'm ok with merging this.

For the record: I wholeheartedly agree. I hope my interest in choice of tools wasn't misunderstood as criticism/pedantry.

**Comment by yarikoptic** [comment]
> I hope my interest in choice of tools wasn't misunderstood as criticism/pedantry.

FWIW, not at all from my side!  I am not "married" to `codespell` - so learning about other handy tools is only useful... may be at some point I will even have a closer/2nd look at pyspelling.

**Pull request merged**
