### PR TITLE
doc: add link to bibtex-to-cff converter

### PR DESCRIPTION
**Pull request by monperrus**
**Problem addressed**: there was no tool to convert bibtex to cff

**Change made in this pull request**: add link to bibtex-to-cff converter

**Review checklist**

- [x] Please check if the pull request is against the correct branch  
(format/schema/semantic documentation changes: `develop`; typos, meta files, etc.: `main`)
- [x] Please check if all changes are recorded in `CHANGELOG.md` and adapt if necessary.
- [x] Please run tests locally.

### CODE REVIEW

**Comment by jspaaks** [comment]
Hi Martin, thanks for making the PR. The README (https://github.com/monperrus/bibtexbrowser/tree/f670ed880b0329c77a78a1e73e40d4fee1c13886#how-to-embed-bibtexbrowser-into-a-website) says `bibtexbrowser` is also usable as a library. Perhaps that warrants adding another row for PHP in between Javascript and Python?

**Comment by monperrus** [comment]
Good idea, thanks for the suggestion @jspaaks. Done

**Comment by jspaaks** [comment]
BTW I'll re-add the cli entry momentarily

**Comment by monperrus** [comment]
thanks a lot @jspaaks

**Pull request merged**
