### PR TITLE
Added more examples

### PR DESCRIPTION
**Pull request by jspaaks**
**Related issues**

Refs: #194 #213 PR #211

~~Branched of off `209-examples`/ PR #211, so probably wise to merge that one first, then merge 1.2.0 into this branch, then undraft this one.~~ done

**Describe the changes made in this pull request**

This PR adds the examples from 1.0.3 as well as those from sibling repo `ruby-cff` as new fixtures under `examples/1.2.0/{pass,fail}`

**Instructions to review the pull request**

```
python3 -m venv env
source env/bin/activate
pip install --upgrade pip wheel setuptools
pip install -r requirements.txt
pytest
```
(should now show more tests for 1.2.0)

Also note there are now 3 tests which should pass but fail. Might need updating here or over at ruby-cff:

1. `./examples/1.2.0/pass/tue-excellent-buildings/bso-toolbox/CITATION.cff`

    https://github.com/citation-file-format/citation-file-format/tree/151ba24711caad3d6e9e53b8e36257fc4682fc90/examples/1.2.0/fail/tue-excellent-buildings/bso-toolbox-invalid-version
1. `./examples/1.2.0/pass/esalmela/haplowinder/CITATION.cff`
 
    https://github.com/citation-file-format/citation-file-format/tree/151ba24711caad3d6e9e53b8e36257fc4682fc90/examples/1.2.0/fail/esalmela/haplowinder

1. `./examples/1.2.0/pass/ls1mardyn/ls1-mardyn/CITATION.cff`

    https://github.com/citation-file-format/citation-file-format/tree/151ba24711caad3d6e9e53b8e36257fc4682fc90/examples/1.2.0/fail/ls1mardyn/ls1-mardyn

### CODE REVIEW

**Comment by sdruskat** [comment]
> Also note there are now 3 tests which should pass but fail. Might need updating here or over at ruby-cff:
> 
>     1. `./examples/1.2.0/pass/tue-excellent-buildings/bso-toolbox/CITATION.cff`
>        validation fails with msg "X is not of type 'str'."

`version` value is a float, not a string (`1.0`), therefore not a valid CFF file.

https://github.com/citation-file-format/citation-file-format/blob/23dd91739c9a32a6745ea52ad1beeb659d0e656e/examples/1.2.0/pass/tue-excellent-buildings/bso-toolbox/CITATION.cff#L10

>     2. `./examples/1.2.0/pass/esalmela/haplowinder/CITATION.cff`
>        validation fails with msg "X is not of type 'str'."

`version` value is a float, not a string (`1.11`), therefore not a valid CFF file

https://github.com/citation-file-format/citation-file-format/blob/e9b1e6d212dd63105de057b0de6fe2838e3f380c/examples/1.2.0/pass/esalmela/haplowinder/CITATION.cff#L8

3. is self-explanatory, and is not a valid CFF file, not even under old schemas.

**Comment by sdruskat** [comment]
@jspaaks Should we have a video call to discuss how to go about this?

**Review by sdruskat — CHANGES_REQUESTED** [review]
Please:

- Use failing CFFs in fail
- Use corrected failing CFFs in pass

**Comment by jspaaks** [comment]
I copied the 3 ruby-cff real-world example files to both `examples/1.2.0/pass` and `examples/1.2.0/fail`, updated the `CITATION.cff` files under `pass/` but not under `fail/`, and documented what I changed in the repsective READMEs.

**Review by sdruskat — APPROVED** [review]
Looks good to me, thanks!
I think the next steps after merging this would be to merge the linter PR (#201), watch it fail, then merge the sorting PR (#218), then watch the linter pass?

**Comment by jspaaks** [comment]
Thanks for the review!

**Pull request merged**
